### ISSUE TITLE
Overlay widget #wishlist

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#69] opened 2017-05-19 13:56 UTC
To successfully implement correlation workflows between different measurements we will need a way to overlay visible/IR visible/<something> and <A>/<B> images. 

A widget like this would take inputs from the hyperspectra and image reader widgets and rescale and overlay the inputs with different opacities.

**Comment by markotoplak** [comment] 2020-01-14 13:42
Duplicate of #118

**Closed by markotoplak** 2020-01-14 13:42 UTC
