### ISSUE TITLE
Dependency on a binary package: opusFC

### ISSUE THREAD

**Issue by yurivict** [Quasars/orange-spectroscopy#190] opened 2018-06-21 03:25 UTC
https://github.com/Quasars/orange-spectroscopy/blob/master/setup.py#L134

PyPI website doesn't provide the source tarball https://pypi.org/project/opusFC/#files
There is no meaningful upstream URL there either.
So the package can't be built, and ```orange-spectroscopy``` can't be installed through the package.

**Comment by scott-cls** [comment] 2018-06-21 14:59
Due to sensitive information in the source code for this project, a source tarball WILL NOT be provided.

We will look into the problem you are having.  Thanks.

**Comment by stuart-cls** [comment] 2018-06-21 15:04
Let's continue this in the opusFC-dist issue. Thanks for your report.

**Comment by markotoplak** [comment] 2018-06-21 16:55
Reopening, as I think this issue is valid. I believe it is wrong that we depend on a binary package (a user can have a platform where there is no binary for or prefers not to use binaries altogether).

I propose removing opusFC from dependencies. The interested users could either:
1. Install opusFC themselves, perhaps the easiest option would be to use Orange's add-ons dialog.
2. When we release it (plan: August), use a pre-packaged version of the Orange + Orange Spectroscopy + opusFC + whatever we want. 

To support (1) we could rewrite file readers so that they would still offer to open Opus files, but if a user tried to open such file, we could ask him to install the opusFC library.

I do not think removing a dependency is a problem, as most of less computer savvy users will probably use (2) anyway.

**Comment by yurivict** [comment] 2018-06-21 17:05
There should be the open source alternative for such a common task as reading some file format.
The FreeBSD ports can't use binary python packages.

**Comment by stuart-cls** [comment] 2018-06-21 19:14
@markotoplak This is fine with me, as long as we can provide non-expert users with a simple way to install. 

The big question, who will do this?

PS this is basically a duplicate of #51

**Comment by yurivict** [comment] 2018-06-21 19:57
> Had we provided the source code the format itself will be exposed.

The veracity of this statements depends on the way how the file format is parsed.
Imagine a flex/bison parser of some file format. Providing the generated parsing tables doesn't actually expose the format.

-----

If in addition to just installing a package some custom extra-actions would be required, like installing some custom binary package, accepting a license, etc, this would reduce the motivation to use it by a lot.

**Comment by borondics** [comment] 2018-06-21 19:59
Thanks for the comment! Guys, what do you think?

**Closed** 2019-01-15 12:56 UTC
